// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImageUrlByPokemon(arg1:number):Promise<Array<string>>;

export function GetPokemonList():Promise<Array<main.Pokemons>>;
