// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageUrlByPokemon(arg1) {
  return window['go']['main']['App']['GetImageUrlByPokemon'](arg1);
}

export function GetPokemonList() {
  return window['go']['main']['App']['GetPokemonList']();
}
